/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laundry;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.Normalizer;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kalilinux
 */
public class Mylaundry extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mylaundry.class.getName());

    /**
     * Creates new form Mylaundry
     */
    public Mylaundry() {
        initComponents();
        Tampilkan_Data();
    }
    
    public int Total_Harga;
    
    private String id_transaksi = "";
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmodel;
    

    public void reset() {
        combo_jenis.setSelectedItem("Pilih Jenis");
        txt_harga.setText("");
        txt_berat.setText("");
        txt_ttlharga.setText("");
        txt_bayar.setText("");
}   
    
    public void Tampilkan_Data() {

    String[] Data = {
    "ID Transaksi",
    "Jenis Cuci",
    "Harga/Kg",
    "Berat(Kg)",
    "Total Harga",
    "Bayar",
    "Kembalian"
};

    tabmodel = new DefaultTableModel(null, Data);
    tabel_data.setModel(tabmodel);

    String sql = "select * from data_laundry";

    try {

        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {

            String FieldId = String.valueOf(
                    hasil.getInt("field_id"));

            String JenisCuci =
                    hasil.getString("jenis_cuci");

            String Harga =
                    hasil.getString("harga");

            String Berat =
                    hasil.getString("berat");

            String TotalHarga =
                    hasil.getString("total_harga");

            String Bayar =
                    hasil.getString("bayar");
            
            String Kembalian =
                    hasil.getString("kembalian");

            String[] DataLaundry = {
                    FieldId,
                    JenisCuci,
                    Harga,
                    Berat,
                    TotalHarga,
                    Bayar,
                    Kembalian
            };

            tabmodel.addRow(DataLaundry);
        }

    } catch (SQLException ex) {

        Logger.getLogger(Mylaundry.class.getName())
        .log(Level.SEVERE, null, ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        combo_jenis = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        txt_ttlharga = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Carlito", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MY LAUNDRY");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 80));

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bayar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Cuci");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga /Kg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        jLabel5.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Berat(Kg)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        txt_bayar.addActionListener(this::txt_bayarActionPerformed);
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 180, 30));

        combo_jenis.setFont(new java.awt.Font("Carlito", 1, 16)); // NOI18N
        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Cuci Basah", "Cuci Kering", "Cuci Setrika" }));
        combo_jenis.addActionListener(this::combo_jenisActionPerformed);
        jPanel1.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 180, 30));

        txt_harga.addActionListener(this::txt_hargaActionPerformed);
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 180, 30));

        txt_berat.addActionListener(this::txt_beratActionPerformed);
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        jPanel1.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 180, 30));

        txt_ttlharga.addActionListener(this::txt_ttlhargaActionPerformed);
        jPanel1.add(txt_ttlharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 180, 30));

        btn_hapus.setFont(new java.awt.Font("Carlito", 1, 20)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(204, 0, 51));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 110, 40));

        btn_transaksi.setFont(new java.awt.Font("Carlito", 1, 20)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(51, 153, 0));
        btn_transaksi.setText("Transaksi");
        btn_transaksi.addActionListener(this::btn_transaksiActionPerformed);
        jPanel1.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, 40));

        btn_update.setFont(new java.awt.Font("Carlito", 1, 20)); // NOI18N
        btn_update.setForeground(new java.awt.Color(0, 0, 204));
        btn_update.setText("Update");
        btn_update.addActionListener(this::btn_updateActionPerformed);
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        btn_batal.setFont(new java.awt.Font("Carlito", 1, 20)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(204, 0, 0));
        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, 40));

        jLabel7.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Data Laundry");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 350, -1));

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 360, 240));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 530);

        setSize(new java.awt.Dimension(865, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_beratActionPerformed

    private void txt_ttlhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttlhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ttlhargaActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
    try {

        String sql =
        "DELETE FROM data_laundry WHERE field_id=?";

        PreparedStatement stat =
                conn.prepareStatement(sql);

        stat.setString(1, id_transaksi);

        stat.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil dihapus");

        Tampilkan_Data();
        reset();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Hapus gagal : " + e);

    }

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
        String url =
        "INSERT INTO data_laundry " +
        "(jenis_cuci,harga,berat,total_harga,bayar,kembalian) " +
        "VALUES (?,?,?,?,?,?)";

if (combo_jenis.getSelectedItem().equals("Pilih Jenis")
        || txt_harga.getText().isEmpty()
        || txt_berat.getText().isEmpty()
        || txt_ttlharga.getText().isEmpty()
        || txt_bayar.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null,
            "Isi terlebih dahulu semua kolom");

} else {    

    int bayar = Integer.parseInt(txt_bayar.getText());
    int totalHarga = Integer.parseInt(txt_ttlharga.getText());

    int kembalian = bayar - totalHarga;

    try {

        PreparedStatement stat = conn.prepareStatement(url);

        stat.setString(1,
                String.valueOf(combo_jenis.getSelectedItem()));

        stat.setString(2, txt_harga.getText());
        stat.setString(3, txt_berat.getText());
        stat.setString(4, txt_ttlharga.getText());
        stat.setString(5, txt_bayar.getText());
        stat.setString(6, String.valueOf(kembalian));
        
        stat.executeUpdate();

        JOptionPane.showMessageDialog(null,
                "Kembalian Anda :\n" + kembalian);

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(null,
                "Transaksi Gagal" + e);

    }   

    reset();
    Tampilkan_Data();
}
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    if (id_transaksi.equals("")) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu");

    } else {

        try {

            int bayar =
                    Integer.parseInt(txt_bayar.getText());

            int totalHarga =
                    Integer.parseInt(txt_ttlharga.getText());

            int kembalian =
                    bayar - totalHarga;

            String sql =
                    "UPDATE data_laundry SET "
                    + "jenis_cuci=?, "
                    + "harga=?, "
                    + "berat=?, "
                    + "total_harga=?, "
                    + "bayar=?, "
                    + "kembalian=? "
                    + "WHERE field_id=?";

            PreparedStatement stat =
                    conn.prepareStatement(sql);

            stat.setString(1,
                    combo_jenis.getSelectedItem().toString());

            stat.setString(2,
                    txt_harga.getText());

            stat.setString(3,
                    txt_berat.getText());

            stat.setString(4,
                    txt_ttlharga.getText());

            stat.setString(5,
                    txt_bayar.getText());

            stat.setString(6,
                    String.valueOf(kembalian));

            stat.setString(7,
                    id_transaksi);

            stat.executeUpdate();

            JOptionPane.showMessageDialog(
                    null,
                    "Data berhasil diupdate");

            reset();
            Tampilkan_Data();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Update gagal : "
                    + e.getMessage());

        }
    }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
            // TODO add your handling code here:
    String jenis = combo_jenis.getSelectedItem().toString();

    switch (jenis) {

        case "Pilih Jenis":
            txt_harga.setText("0");
            break;

        case "Cuci Basah":
            txt_harga.setText("3000");
            break;

        case "Cuci Kering":
            txt_harga.setText("4000");
            break;

        case "Cuci Setrika":
            txt_harga.setText("5000");
            break;

        default:
            txt_harga.setText("0");
            break;
    }                      
        
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        
    try {

        if(txt_berat.getText().trim().equals("")) {
            txt_ttlharga.setText("0");
            return;
        }

        int harga = Integer.parseInt(txt_harga.getText());
        int berat = Integer.parseInt(txt_berat.getText());

        int totalHarga = harga * berat;

        txt_ttlharga.setText(String.valueOf(totalHarga));

    } catch (NumberFormatException e) {
        txt_ttlharga.setText("0");
    }
    }//GEN-LAST:event_txt_beratKeyReleased

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        // TODO add your handling code here:
    int baris = tabel_data.getSelectedRow();

    id_transaksi =
            tabel_data.getValueAt(baris, 0).toString();

    System.out.println("ID TERPILIH = " + id_transaksi);

    combo_jenis.setSelectedItem(
            tabel_data.getValueAt(baris, 1));

    txt_harga.setText(
            tabel_data.getValueAt(baris, 2).toString());

    txt_berat.setText(
            tabel_data.getValueAt(baris, 3).toString());

    txt_ttlharga.setText(
            tabel_data.getValueAt(baris, 4).toString());

    txt_bayar.setText(
            tabel_data.getValueAt(baris, 5).toString());

    }//GEN-LAST:event_tabel_dataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mylaundry().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_ttlharga;
    // End of variables declaration//GEN-END:variables
}
